# Config file
CLIENT_BIND_IP      = "127.0.0.1"
CLIENT_SEND_PORT    = 5000

SERVER_BIND_IP      = "127.0.0.1"
SERVER_BROADCAST_IP = ""
SERVER_LISTEN_PORT  = 5005

LISTEN_BUFFER_SIZE  = 2**16
TCP_WINDOW_SIZE     = 5

SERVER_TRANSFER_ACK_TIMEOUT = 0.1    # Unit : second


# Bonus
SEND_METADATA   = True
USE_PARALLEL    = True
